import { buildTextNodeMap, getPageLocalRectsFromRange, getTextContext } from "@gs/paper-reader";
import type { PageHandle, PageLocalRect, PdfRect, PdfScaleValue, PdfTextSelection, ViewerAdapter, VisiblePageRef } from "@gs/paper-reader";
export interface DemoPageHandle extends PageHandle { viewport?: { convertToPdfPoint?(x: number, y: number): [number, number]; convertToViewportPoint?(x: number, y: number): [number, number] } }
export class DemoViewerAdapter implements ViewerAdapter {
  readonly pages = new Map<number, DemoPageHandle>(); currentPage = 1; pageCount: number | null = null; scale: PdfScaleValue = "page-width"; onScaleChange?: (scale: PdfScaleValue) => void;
  registerPage(page: DemoPageHandle): void { this.pages.set(page.pageIndex, page); }
  clearPages(): void { this.pages.clear(); this.currentPage = 1; this.pageCount = null; }
  setPageCount(pageCount: number): void { this.pageCount = pageCount; }
  getCurrentPage(): number { return this.currentPage; }
  getPageCount(): number | null { return this.pageCount; }
  goToPage(pageNumber: number): void { const count = this.getPageCount(); const next = count ? Math.max(1, Math.min(pageNumber, count)) : Math.max(1, pageNumber); this.currentPage = next; this.pages.get(next - 1)?.div.scrollIntoView({ block: "start" }); }
  previousPage(): void { this.goToPage(this.currentPage - 1); }
  nextPage(): void { this.goToPage(this.currentPage + 1); }
  getScale(): PdfScaleValue | null { return this.scale; }
  setScale(scale: PdfScaleValue): void { this.scale = scale; this.onScaleChange?.(scale); }
  zoomIn(): void { const current = typeof this.scale === "number" ? this.scale : 1.25; this.setScale(Math.min(3, Number((current + 0.15).toFixed(2)))); }
  zoomOut(): void { const current = typeof this.scale === "number" ? this.scale : 1.25; this.setScale(Math.max(0.4, Number((current - 0.15).toFixed(2)))); }
  getPageHandle(pageIndex: number): DemoPageHandle | null { return this.pages.get(pageIndex) ?? null; }
  getVisiblePages(): VisiblePageRef[] { return Array.from(this.pages.values()).map(page => ({ pageIndex: page.pageIndex, pageNumber: page.pageNumber, percentVisible: 100 })); }
  getSelection(): PdfTextSelection | null { const selection = document.getSelection(); if (!selection || selection.rangeCount === 0 || selection.isCollapsed) return null; const range = selection.getRangeAt(0); const textLayer = this.findTextLayer(range); const pageDiv = textLayer?.closest<HTMLElement>(".page"); if (!textLayer || !pageDiv) return null; const pageIndex = Math.max(0, Number(pageDiv.dataset.pageNumber ?? "1") - 1); const map = buildTextNodeMap(textLayer); const startOffset = this.getOffsetWithin(textLayer, range.startContainer, range.startOffset); const endOffset = this.getOffsetWithin(textLayer, range.endContainer, range.endOffset); if (startOffset === null || endOffset === null) return null; const start = Math.max(0, Math.min(startOffset, endOffset)); const end = Math.max(start, Math.max(startOffset, endOffset)); const page = this.getPageHandle(pageIndex); const rects = getPageLocalRectsFromRange(range, pageDiv).map(rect => this.pageLocalRectToPdfRect(page, rect)); const { textBefore, textAfter } = getTextContext(map.text, start, end); return { pageIndex, startOffset: start, endOffset: end, text: selection.toString().replace(/\s+/g, " ").trim(), textBefore, textAfter, rects }; }
  getSelectionLocalRects(): PageLocalRect[] { const selection = document.getSelection(); if (!selection || selection.rangeCount === 0 || selection.isCollapsed) return []; const range = selection.getRangeAt(0); const pageDiv = this.findTextLayer(range)?.closest<HTMLElement>(".page"); return pageDiv ? getPageLocalRectsFromRange(range, pageDiv) : []; }
  clearSelection(): void { document.getSelection()?.removeAllRanges(); }
  scrollToPageRect(pageIndex: number, rect: PdfRect): void { const page = this.getPageHandle(pageIndex); if (page) this.scrollToPageLocalRect(pageIndex, this.pdfRectToPageLocalRect(page, rect)); }
  scrollToPageLocalRect(pageIndex: number, rect: PageLocalRect): void { const page = this.getPageHandle(pageIndex); if (!page) return; const marker = page.div.ownerDocument.createElement("span"); Object.assign(marker.style, { position: "absolute", left: `${rect.left}px`, top: `${rect.top}px`, width: `${Math.max(1, rect.width)}px`, height: `${Math.max(1, rect.height)}px` }); page.div.append(marker); try { marker.scrollIntoView({ block: "center", inline: "nearest" }); } finally { marker.remove(); } }
  pageLocalRectToPdfRect(page: DemoPageHandle | null, rect: PageLocalRect): PdfRect { if (!page?.viewport?.convertToPdfPoint) return { x: rect.left, y: rect.top, width: rect.width, height: rect.height }; const [x1, y1] = page.viewport.convertToPdfPoint(rect.left, rect.top); const [x2, y2] = page.viewport.convertToPdfPoint(rect.left + rect.width, rect.top + rect.height); return { x: Math.min(x1, x2), y: Math.min(y1, y2), width: Math.abs(x2 - x1), height: Math.abs(y2 - y1) }; }
  pdfRectToPageLocalRect(page: DemoPageHandle, rect: PdfRect): PageLocalRect { if (!page.viewport?.convertToViewportPoint) return { left: rect.x, top: rect.y, width: rect.width, height: rect.height }; const [x1, y1] = page.viewport.convertToViewportPoint(rect.x, rect.y); const [x2, y2] = page.viewport.convertToViewportPoint(rect.x + rect.width, rect.y + rect.height); return { left: Math.min(x1, x2), top: Math.min(y1, y2), width: Math.abs(x2 - x1), height: Math.abs(y2 - y1) }; }
  private findTextLayer(range: Range): HTMLElement | null { for (const node of [range.startContainer, range.endContainer]) { const element = node.nodeType === Node.ELEMENT_NODE ? (node as Element) : node.parentElement; const layer = element?.closest<HTMLElement>(".textLayer"); if (layer) return layer; } return null; }
  private getOffsetWithin(root: HTMLElement, container: Node, offset: number): number | null { if (!root.contains(container)) return null; const range = document.createRange(); range.selectNodeContents(root); try { range.setEnd(container, offset); return range.toString().length; } catch { return null; } finally { range.detach(); } }
}
