import "@gs/paper-reader/styles.css";
import "./styles.css";
import { createPaperReader, type NewReviewAnnotation, type PageLocalRect, type ReviewAnnotation, type SentenceIndex, type SentenceRef } from "@gs/paper-reader";
import { explainText, extractionHint, summarizeText } from "./demo_ai.js";
import { DemoViewerAdapter } from "./demo_viewer_adapter.js";
import { buildDomSentenceIndex, getDomSentenceRects } from "./dom_sentence_focus.js";
import { DemoPdfRenderer } from "./pdf_loader.js";
import { installPdfPinchZoom } from "./pinch_zoom.js";
import { buildPaperStructure, searchSentences } from "./section_index.js";
import { EXTRACTION_FIELDS, type PaperStructureIndex, type RightPanelTab, type ReviewDecisionValue } from "./model.js";

const PAPER_ID = "demo-paper";
const root = document.getElementById("app");
if (!root) throw new Error("Missing #app root");
root.innerHTML = `<div class="demo-shell left-closed right-closed"><header class="demo-toolbar"><strong>GS Paper Reader Demo</strong><label class="demo-file-button">Import PDF<input data-action="file" type="file" accept="application/pdf" hidden /></label><button data-action="zoomOut">−</button><button data-action="zoomIn">+</button><button data-action="prevPage">Prev page</button><button data-action="nextPage">Next page</button><button data-action="focus">Sentence focus</button><button data-action="prevSentence">↑ Sentence</button><button data-action="nextSentence">↓ Sentence</button><button data-action="highlight">Highlight</button><button data-action="evidence">Evidence</button><button data-action="note">Note</button><button data-action="ai">Ask AI</button><button data-action="copy">Copy citation</button></header><button class="demo-side-toggle demo-side-toggle-left" data-action="toggleLeft">☰</button><button class="demo-side-toggle demo-side-toggle-right" data-action="toggleRight">☰</button><div class="demo-workspace"><aside class="demo-left-panel"></aside><main class="demo-viewer-wrap"><div class="demo-viewer"></div><div class="demo-floating-menu" hidden></div></main><aside class="demo-right-panel"></aside></div><footer class="demo-status">Import a PDF to start.</footer></div>`;
const shell = document.querySelector<HTMLElement>(".demo-shell")!;
const viewerWrap = document.querySelector<HTMLElement>(".demo-viewer-wrap")!;
const viewer = new DemoViewerAdapter();
const renderer = new DemoPdfRenderer(document.querySelector<HTMLElement>(".demo-viewer")!, viewer);
let reader: ReturnType<typeof createPaperReader> | null = null;
let sentenceIndex: SentenceIndex | null = null;
let sentenceRefs: readonly SentenceRef[] = [];
let structure: PaperStructureIndex = { sections: [], visuals: [], references: [] };
let pagesText: Array<{ pageIndex: number; text: string }> = [];
let activeTab: RightPanelTab = "notes";
let lastSentence: SentenceRef | null = null;
let unbindKeyboard: (() => void) | null = null;
let metadata = { title: "No PDF loaded", sourceName: "", pageCount: 0, loadedAt: "" };
let decision: { value: ReviewDecisionValue; reason: string } = { value: "unreviewed", reason: "" };
const annotations: Array<{ annotation: ReviewAnnotation; pageLocalRects: PageLocalRect[] }> = [];
const annotationAnchors = new Map<string, { pageIndex: number; startOffset: number; endOffset: number }>();
const evidenceCards: unknown[] = [];
const aiSuggestions: Array<{ id: string; kind: string; answer: string; confirmed: boolean }> = [];
const extractionValues = new Map<string, string>();
const status = document.querySelector<HTMLElement>(".demo-status")!;
const leftPanel = document.querySelector<HTMLElement>(".demo-left-panel")!;
const rightPanel = document.querySelector<HTMLElement>(".demo-right-panel")!;
const floatingMenu = document.querySelector<HTMLElement>(".demo-floating-menu")!;
viewer.onScaleChange = scale => void reload(typeof scale === "number" ? Number(scale) : 1.25);
document.querySelector(".demo-toolbar")?.addEventListener("click", event => { const action = (event.target as HTMLElement).closest<HTMLElement>("[data-action]")?.dataset.action; if (action && action !== "file") void run(action); });
document.querySelectorAll<HTMLElement>(".demo-side-toggle").forEach(button => button.addEventListener("click", () => void run(button.dataset.action ?? "")));
document.querySelector<HTMLInputElement>("[data-action='file']")?.addEventListener("change", event => { const file = (event.target as HTMLInputElement).files?.[0]; if (file) void file.arrayBuffer().then(buffer => loadPdf(new Uint8Array(buffer), file.name)); });
document.addEventListener("selectionchange", updateFloatingMenu);
document.addEventListener("pointerdown", event => { const target = event.target as Node; if (!floatingMenu.hidden && !floatingMenu.contains(target) && !(target instanceof Element && target.closest(".textLayer"))) floatingMenu.hidden = true; });
installPdfPinchZoom({ target: viewerWrap, getScale: () => typeof viewer.getScale() === "number" ? Number(viewer.getScale()) : 1.25, setScale: scale => viewer.setScale(scale) });
async function run(action: string): Promise<void> { if (action === "toggleLeft") shell.classList.toggle("left-closed"); if (action === "toggleRight") shell.classList.toggle("right-closed"); if (action === "zoomIn") viewer.zoomIn(); if (action === "zoomOut") viewer.zoomOut(); if (action === "prevPage") viewer.previousPage(); if (action === "nextPage") viewer.nextPage(); if (action === "focus") toggleFocus(); if (action === "prevSentence") moveSentence(-1); if (action === "nextSentence") moveSentence(1); if (action === "highlight") await annotate("highlight"); if (action === "note") await annotate("note", prompt("Note", "") ?? ""); if (action === "evidence") await createEvidence(); if (action === "ai") askAi(); if (action === "copy") await copyCitation(); }
function rebuildDomIndex(): void { const dom = buildDomSentenceIndex(viewer); sentenceIndex = dom.index; sentenceRefs = dom.sentences; structure = buildPaperStructure(sentenceRefs); }
function recreateReader(): void { if (!sentenceIndex) return; unbindKeyboard?.(); reader = createPaperReader({ viewer, sentenceIndex }); unbindKeyboard = reader.sentenceFocus.bindKeyboard(document); }
async function loadPdf(bytes: Uint8Array, sourceName: string): Promise<void> { const result = await renderer.load(bytes, sourceName, typeof viewer.getScale() === "number" ? Number(viewer.getScale()) : 1.25); pagesText = result.pageTexts; rebuildDomIndex(); metadata = { title: result.title.replace(/\.pdf$/i, ""), sourceName, pageCount: result.pageCount, loadedAt: new Date().toISOString() }; annotations.length = 0; annotationAnchors.clear(); evidenceCards.length = 0; aiSuggestions.length = 0; extractionValues.clear(); decision = { value: "unreviewed", reason: "" }; recreateReader(); renderPanels(); status.textContent = `Loaded ${sourceName}: ${result.pageCount} pages, ${sentenceRefs.length} DOM-indexed sentences.`; }
async function reload(scale: number): Promise<void> { const result = await renderer.rerender(scale); if (!result) return; pagesText = result.pageTexts; rebuildDomIndex(); recreateReader(); await renderAnnotationOverlays(); renderPanels(); }
function toggleFocus(): void { if (!reader) return; if (reader.sentenceFocus.state.enabled) { reader.sentenceFocus.disable(); status.textContent = "Sentence focus off."; return; } lastSentence = reader.sentenceFocus.enable(lastSentence?.id); status.textContent = "Sentence focus on."; }
function moveSentence(delta: -1 | 1): void { if (!reader) return; lastSentence = reader.sentenceFocus.move(delta); if (lastSentence) status.textContent = `Focused sentence ${lastSentence.ordinal + 1}.`; }
function focusSentence(id: string): void { const sentence = sentenceIndex?.getById(id); if (sentence && reader) { reader.sentenceFocus.enable(sentence.id); lastSentence = sentence; } }
async function annotate(type: NewReviewAnnotation["type"], note?: string) { if (!reader) return null; const selection = viewer.getSelection(); const localRects = viewer.getSelectionLocalRects(); if (!selection?.text || localRects.length === 0) { status.textContent = "Select text first."; return null; } const input: NewReviewAnnotation = { paperId: PAPER_ID, type, pageIndex: selection.pageIndex, rectsPdfSpace: selection.rects, text: selection.text, createdBy: "demo-user" }; if (note) input.note = note; const annotation = await reader.annotations.create(input); annotationAnchors.set(annotation.id, { pageIndex: selection.pageIndex, startOffset: selection.startOffset, endOffset: selection.endOffset }); annotations.unshift({ annotation, pageLocalRects: localRects }); viewer.clearSelection(); floatingMenu.hidden = true; await renderAnnotationOverlays(); renderPanels(); return annotation; }
async function createEvidence(): Promise<void> { if (!reader) return; const annotation = await annotate("evidence", "Evidence from selected quote."); if (!annotation) return; evidenceCards.unshift(reader.evidence.fromAnnotation({ annotation, evidenceType: "result", confidence: "medium" })); activeTab = "evidence"; floatingMenu.hidden = true; renderPanels(); }
async function renderAnnotationOverlays(): Promise<void> { reader?.overlays.clear(undefined, "annotation"); for (const record of annotations) { const anchor = annotationAnchors.get(record.annotation.id); const rects = anchor ? getDomSentenceRects(viewer, { id: record.annotation.id, ordinal: 0, pageIndex: anchor.pageIndex, startOffset: anchor.startOffset, endOffset: anchor.endOffset, text: record.annotation.text }) : record.pageLocalRects; reader?.overlays.render({ pageIndex: record.annotation.pageIndex, kind: "annotation", rects: rects.length ? rects : record.pageLocalRects, dataset: { annotationId: record.annotation.id } }); } }
function askAi(): void { const selection = viewer.getSelection(); const source = selection?.text || lastSentence?.text || pagesText.find(page => page.pageIndex === viewer.getCurrentPage() - 1)?.text || ""; if (!source) return; aiSuggestions.unshift({ id: `ai-${aiSuggestions.length + 1}`, kind: selection?.text ? "explain" : "summarize", answer: selection?.text ? explainText(source) : summarizeText(source), confirmed: false }); activeTab = "ai"; floatingMenu.hidden = true; renderPanels(); }
async function copyCitation(): Promise<void> { const selection = viewer.getSelection(); if (!selection?.text) return; await navigator.clipboard?.writeText(`"${selection.text}" (${metadata.title}, p. ${selection.pageIndex + 1})`); floatingMenu.hidden = true; viewer.clearSelection(); }
function updateFloatingMenu(): void { const selection = viewer.getSelection(); const range = document.getSelection()?.rangeCount ? document.getSelection()?.getRangeAt(0) : null; const rect = range?.getBoundingClientRect(); if (!selection?.text || !rect) { floatingMenu.hidden = true; return; } floatingMenu.innerHTML = `<button data-float="highlight">Highlight</button><button data-float="evidence">Evidence</button><button data-float="note">Note</button><button data-float="ai">Ask AI</button><button data-float="copy">Copy citation</button>`; Object.assign(floatingMenu.style, { left: `${Math.max(8, rect.left)}px`, top: `${Math.max(8, rect.top - 44)}px` }); floatingMenu.hidden = false; floatingMenu.querySelectorAll<HTMLElement>("[data-float]").forEach(button => button.addEventListener("click", () => void run(button.dataset.float ?? "highlight"))); }
function renderPanels(): void { renderLeftPanel(); renderRightPanel(); }
function renderLeftPanel(): void { leftPanel.innerHTML = `<h3>Navigation</h3><input class="demo-search-input" placeholder="Search sentences" /><div data-search-results></div><h4>Sections</h4>${structure.sections.map(s => `<button class="demo-list-item" data-sentence="${s.sentenceId}">${s.title}<small>Page ${s.pageIndex + 1}</small></button>`).join("")}<h4>Figures / Tables</h4>${structure.visuals.map(v => `<button class="demo-list-item" data-sentence="${v.sentenceId}">${v.label}<small>${escapeHtml(v.caption)}</small></button>`).join("") || "<p>No visuals detected.</p>"}<h4>References</h4>${structure.references.map(r => `<button class="demo-list-item" data-sentence="${r.sentenceId}">${r.label}<small>${escapeHtml(r.text)}</small></button>`).join("") || "<p>No references detected.</p>"}`; bindSentenceButtons(leftPanel); const input = leftPanel.querySelector<HTMLInputElement>(".demo-search-input")!; const results = leftPanel.querySelector<HTMLElement>("[data-search-results]")!; input.addEventListener("input", () => { results.innerHTML = searchSentences(sentenceRefs, input.value).map(hit => `<button class="demo-list-item" data-sentence="${hit.sentence.id}">${escapeHtml(hit.preview)}<small>Page ${hit.sentence.pageIndex + 1}</small></button>`).join(""); bindSentenceButtons(results); }); }
function bindSentenceButtons(container: HTMLElement): void { container.querySelectorAll<HTMLElement>("[data-sentence]").forEach(button => button.addEventListener("click", () => focusSentence(button.dataset.sentence ?? ""))); }
function renderRightPanel(): void { const tabs: RightPanelTab[] = ["notes", "evidence", "ai", "extraction", "decision", "metadata"]; rightPanel.innerHTML = `<nav class="demo-tabs">${tabs.map(tab => `<button class="${tab === activeTab ? "active" : ""}" data-tab="${tab}">${tab}</button>`).join("")}</nav><div class="demo-panel-body"></div>`; rightPanel.querySelectorAll<HTMLElement>("[data-tab]").forEach(button => button.addEventListener("click", () => { activeTab = button.dataset.tab as RightPanelTab; renderRightPanel(); })); const body = rightPanel.querySelector<HTMLElement>(".demo-panel-body")!; if (activeTab === "notes") body.innerHTML = annotations.map(r => `<article class="demo-card"><strong>${r.annotation.type}</strong><p>${escapeHtml(r.annotation.text)}</p></article>`).join("") || "<p>Create notes from text selection.</p>"; else if (activeTab === "evidence") body.innerHTML = evidenceCards.map(card => `<article class="demo-card"><pre>${escapeHtml(JSON.stringify(card, null, 2))}</pre></article>`).join("") || "<p>No evidence yet.</p>"; else if (activeTab === "ai") body.innerHTML = `<button data-ai>Generate suggestion</button>${aiSuggestions.map(s => `<article class="demo-card"><strong>${s.kind}</strong><p>${escapeHtml(s.answer)}</p><button data-confirm-ai="${s.id}">${s.confirmed ? "Confirmed" : "Confirm"}</button></article>`).join("")}`; else if (activeTab === "extraction") body.innerHTML = EXTRACTION_FIELDS.map(f => `<label class="demo-field"><span>${f.label}</span><small>${f.help}</small><textarea data-extraction="${f.id}">${escapeHtml(extractionValues.get(f.id) ?? "")}</textarea><button data-fill="${f.id}">Fill from selection</button></label>`).join(""); else if (activeTab === "decision") body.innerHTML = `<select data-decision>${["unreviewed", "accept", "reject", "maybe"].map(v => `<option ${decision.value === v ? "selected" : ""}>${v}</option>`).join("")}</select><textarea data-reason>${escapeHtml(decision.reason)}</textarea><button data-save-decision>Save decision</button>`; else body.innerHTML = `<dl class="demo-metadata"><dt>Title</dt><dd>${metadata.title}</dd><dt>Pages</dt><dd>${metadata.pageCount}</dd><dt>Sentences</dt><dd>${sentenceRefs.length}</dd></dl><textarea readonly>${escapeHtml(JSON.stringify({ metadata, decision, annotations, evidenceCards, aiSuggestions, extractionValues: Array.from(extractionValues.entries()) }, null, 2))}</textarea>`; wireRightPanel(body); }
function wireRightPanel(body: HTMLElement): void { body.querySelector<HTMLElement>("[data-ai]")?.addEventListener("click", askAi); body.querySelectorAll<HTMLElement>("[data-confirm-ai]").forEach(b => b.addEventListener("click", () => { const s = aiSuggestions.find(x => x.id === b.dataset.confirmAi); if (s) s.confirmed = true; renderRightPanel(); })); body.querySelectorAll<HTMLTextAreaElement>("[data-extraction]").forEach(input => input.addEventListener("change", () => extractionValues.set(input.dataset.extraction ?? "", input.value))); body.querySelectorAll<HTMLElement>("[data-fill]").forEach(b => b.addEventListener("click", () => { const s = viewer.getSelection(); if (s?.text) extractionValues.set(b.dataset.fill ?? "", extractionHint(s.text)); renderRightPanel(); })); body.querySelector<HTMLElement>("[data-save-decision]")?.addEventListener("click", () => { decision = { value: body.querySelector<HTMLSelectElement>("[data-decision]")!.value as ReviewDecisionValue, reason: body.querySelector<HTMLTextAreaElement>("[data-reason]")!.value }; }); }
function escapeHtml(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }
renderPanels();
