import * as pdfjs from "pdfjs-dist";
import pdfWorkerSrc from "pdfjs-dist/build/pdf.worker.mjs?url";
import type { DemoPageHandle, DemoViewerAdapter } from "./demo_viewer_adapter.js";
(pdfjs.GlobalWorkerOptions as { workerSrc: string }).workerSrc = pdfWorkerSrc;
type PdfDocumentProxy = any;
type TextContent = { items: Array<Record<string, unknown>> };
export interface LoadedPdfResult { title: string; pageTexts: Array<{ pageIndex: number; text: string }>; pageCount: number }
export class DemoPdfRenderer {
  private pdf: PdfDocumentProxy | null = null;
  constructor(private readonly container: HTMLElement, private readonly viewer: DemoViewerAdapter) {}
  async load(bytes: Uint8Array, title: string, scale = 1.25): Promise<LoadedPdfResult> { this.container.replaceChildren(); this.viewer.clearPages(); this.pdf = await pdfjs.getDocument({ data: bytes.slice() }).promise; this.viewer.setPageCount(this.pdf.numPages); const pageTexts: Array<{ pageIndex: number; text: string }> = []; for (let pageNumber = 1; pageNumber <= this.pdf.numPages; pageNumber += 1) { const page = await this.pdf.getPage(pageNumber); pageTexts.push({ pageIndex: pageNumber - 1, text: await this.renderPage(page, pageNumber, scale) }); } return { title, pageTexts, pageCount: this.pdf.numPages }; }
  async rerender(scale: number): Promise<LoadedPdfResult | null> { if (!this.pdf) return null; this.container.replaceChildren(); this.viewer.clearPages(); this.viewer.setPageCount(this.pdf.numPages); const pageTexts: Array<{ pageIndex: number; text: string }> = []; for (let pageNumber = 1; pageNumber <= this.pdf.numPages; pageNumber += 1) { const page = await this.pdf.getPage(pageNumber); pageTexts.push({ pageIndex: pageNumber - 1, text: await this.renderPage(page, pageNumber, scale) }); } return { title: "Current PDF", pageTexts, pageCount: this.pdf.numPages }; }
  private async renderPage(page: any, pageNumber: number, scale: number): Promise<string> { const viewport = page.getViewport({ scale }); const pageDiv = document.createElement("section"); pageDiv.className = "page demo-pdf-page"; pageDiv.dataset.pageNumber = String(pageNumber); pageDiv.style.width = `${Math.floor(viewport.width)}px`; pageDiv.style.height = `${Math.floor(viewport.height)}px`; const canvas = document.createElement("canvas"); const context = canvas.getContext("2d"); if (!context) throw new Error("Could not create canvas context"); const outputScale = window.devicePixelRatio || 1; canvas.width = Math.floor(viewport.width * outputScale); canvas.height = Math.floor(viewport.height * outputScale); canvas.style.width = `${Math.floor(viewport.width)}px`; canvas.style.height = `${Math.floor(viewport.height)}px`; pageDiv.append(canvas); const textLayerDiv = document.createElement("div"); textLayerDiv.className = "textLayer demo-text-layer"; pageDiv.append(textLayerDiv); const annotationLayerDiv = document.createElement("div"); annotationLayerDiv.className = "annotationLayer demo-native-annotation-layer"; pageDiv.append(annotationLayerDiv); this.container.append(pageDiv); await page.render({ canvasContext: context, transform: outputScale !== 1 ? [outputScale, 0, 0, outputScale, 0, 0] : undefined, viewport }).promise; const textContent = (await page.getTextContent()) as TextContent; await this.renderTextLayer(textLayerDiv, textContent, viewport); const pageHandle: DemoPageHandle = { pageIndex: pageNumber - 1, pageNumber, div: pageDiv, textLayerDiv, viewport }; this.viewer.registerPage(pageHandle); return textContent.items.map(item => String(item.str ?? "")).filter(Boolean).join(" ").replace(/\s+/g, " ").trim(); }
  private async renderTextLayer(container: HTMLElement, textContent: TextContent, viewport: unknown): Promise<void> { const TextLayer = (pdfjs as unknown as { TextLayer?: new (params: Record<string, unknown>) => { render(): Promise<void> } }).TextLayer; if (TextLayer) { await new TextLayer({ textContentSource: textContent, container, viewport }).render(); return; } for (const item of textContent.items) { const str = String(item.str ?? ""); if (!str) continue; const span = document.createElement("span"); span.textContent = str; span.style.position = "absolute"; container.append(span); } }
}
